server:
  port: 10020

spring:
  application:
    name: service-system  # 服务名
  datasource:
    url: jdbc:mysql:///ymcc-system?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mybatis-plus:
    mapper-locations: classpath:cn/guoche/ymcc/mapper/*Mapper.xml

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  main:
    allow-bean-definition-overriding: true
